# Generated by Django 4.2.5 on 2023-09-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_database_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='course',
            new_name='category',
        ),
    ]
